queries = [
    {"query": "iosdfjsoidfjoimlsamoidf", "expected_result": "doc1"},
    {"query": "Joseph is enjoying morning food", "expected_result": "doc1"},
    {"query": "Terminids are a threat to the whole galaxy even for the robots", "expected_result": "doc2"},
    {"query": "Joachim is not here today. He went to NASA to apply for a job.", "expected_result": "doc2"},
    {"query": "She's a weakling when it comes to weather forecasting", "expected_result": "doc2"},

    # New test cases
    {"query": "What should I wear if it rains tomorrow?", "expected_result": "doc2"},
    {"query": "Scrambled eggs are my go-to breakfast choice.", "expected_result": "doc1"},
    {"query": "Rainy days make the streets quiet and peaceful.", "expected_result": "doc2"},
    {"query": "I usually drink coffee with pancakes in the morning.", "expected_result": "doc1"},
    {"query": "Forecast says it might snow next week.", "expected_result": "doc2"},
    {"query": "The sun rises beautifully over a plate of hot eggs.", "expected_result": "doc1"},
    {"query": "Cloudy skies often bring cooler temperatures.", "expected_result": "doc2"},
    {"query": "Do you prefer waffles or pancakes for breakfast?", "expected_result": "doc1"},
    {"query": "High humidity tomorrow with chance of rain.", "expected_result": "doc2"},
    {"query": "My morning started with toast and warm tea.", "expected_result": "doc1"},
    {"query": "The skies will be partially cloudy with intermittent light rain throughout the afternoon.", "expected_result": "doc2"},
    {"query": "Fried eggs and buttered toast are the best way to kick off a Monday.", "expected_result": "doc1"},
    {"query": "Meteorologists predict a significant drop in temperature by nightfall.", "expected_result": "doc2"},
    {"query": "I topped my pancakes with strawberries and whipped cream this morning.", "expected_result": "doc1"},
    {"query": "Expect thunderstorms in the early hours with clearing skies by noon.", "expected_result": "doc2"},
    {"query": "Nothing beats a hearty breakfast with bacon, eggs, and hash browns.", "expected_result": "doc1"},
    {"query": "A cold front is moving in from the north, bringing heavy winds and fog.", "expected_result": "doc2"},
    {"query": "This morning I made French toast sprinkled with cinnamon and powdered sugar.", "expected_result": "doc1"},
    {"query": "Tomorrow’s forecast includes scattered showers and high humidity levels.", "expected_result": "doc2"},
    {"query": "We had oatmeal with raisins and honey before heading out for the day.", "expected_result": "doc1"},
]